### ISSUE TITLE
I see all icons double

### ISSUE THREAD

**Issue by gerard-kanters** [ColdTrick/fontawesome#4]
In elgg 1.12 I see all icons double in the river. See below picture . There is a dependancy with HypeWall where you can only see the sharing icons, so I do seem to need this plugin. Any ideas ?

![capture](https://cloud.githubusercontent.com/assets/4699801/13580766/ea0ac3dc-e4a3-11e5-8393-559d89a9d87b.PNG)

**Comment by jdalsem** [comment]
You are seeing both the font-awesome icons and the elgg icons (images). What is the html for these icons? And the related css?

**Comment by gerard-kanters** [comment]
You mean this ?

`<span class="elgg-icon-speech-bubble elgg-icon fa fa-comment"></span>

element.style {
}
.fa {
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
.elgg-icon-speech-bubble {
    background-position: 0 -1134px;
}
.elgg-icon {
    background: transparent url(https://www.centillien.com/_graphics/elgg_sprites.png) no-repeat left;
    width: 16px;
    height: 16px;
    margin: 0 2px;
}

`

**Comment by jdalsem** [comment]
is font awesome the last plugin? the .elgg-icon class should not contain the reference to the background sprite..

**Comment by gerard-kanters** [comment]
Yes, that's it. It was below aalborg_theme but in the site_plugin I override the css again. Thanks, I should have thought of that myself.
